
// Generated by Cadence Encounter(R) RTL Compiler RC14.10 - v14.10-p008_1

// Verification Directory fv/controller 

module controller(clk, t10, t15, t20, t25, t30, reset, heat, fan, ac);
  input clk, t10, t15, t20, t25, t30, reset;
  output heat, fan, ac;
  wire clk, t10, t15, t20, t25, t30, reset;
  wire heat, fan, ac;
  wire [2:0] next_state;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65;
  assign next_state[2] = 1'b0;
  assign next_state[1] = 1'b0;
  assign next_state[0] = 1'b0;
  assign ac = 1'b0;
  assign fan = 1'b0;
  assign heat = 1'b0;
  DFFHQX1 \next_state_reg[0]406 (.CK (clk), .D (n_64), .Q
       (next_state[0]));
  DFFHQX1 \next_state_reg[1]407 (.CK (clk), .D (n_65), .Q
       (next_state[1]));
  DFFHQX1 heat_reg400(.CK (clk), .D (n_61), .Q (heat));
  DFFHQX1 ac_reg404(.CK (clk), .D (n_62), .Q (ac));
  DFFHQX1 fan_reg402(.CK (clk), .D (n_63), .Q (fan));
  OAI211X1 g2134(.A0 (n_53), .A1 (reset), .B0 (n_31), .C0 (n_58), .Y
       (n_65));
  OAI211X1 g2135(.A0 (n_3), .A1 (n_31), .B0 (n_39), .C0 (n_59), .Y
       (n_64));
  OAI2BB1X1 g2136(.A0N (fan), .A1N (n_1), .B0 (n_49), .Y (n_63));
  OAI21XL g2137(.A0 (n_36), .A1 (n_30), .B0 (n_60), .Y (n_62));
  AO22X1 g2138(.A0 (heat), .A1 (n_55), .B0 (n_38), .B1 (n_29), .Y
       (n_61));
  DFFHQX1 \next_state_reg[2]408 (.CK (clk), .D (n_57), .Q
       (next_state[2]));
  NAND2XL g2140(.A (ac), .B (n_56), .Y (n_60));
  AOI221X1 g2141(.A0 (n_2), .A1 (n_50), .B0 (n_8), .B1 (n_45), .C0
       (n_51), .Y (n_59));
  AOI22XL g2142(.A0 (n_9), .A1 (n_54), .B0 (t30), .B1 (n_45), .Y
       (n_58));
  OAI211X1 g2143(.A0 (n_43), .A1 (reset), .B0 (n_44), .C0 (n_40), .Y
       (n_57));
  NAND4XL g2145(.A (n_7), .B (n_33), .C (n_34), .D (n_48), .Y (n_56));
  NAND4XL g2146(.A (n_9), .B (n_23), .C (n_46), .D (n_48), .Y (n_55));
  OAI2BB1X1 g2147(.A0N (n_27), .A1N (n_6), .B0 (n_52), .Y (n_54));
  NAND2XL g2148(.A (next_state[1]), .B (n_41), .Y (n_53));
  OAI21XL g2149(.A0 (n_4), .A1 (n_32), .B0 (next_state[1]), .Y (n_52));
  NOR2XL g2150(.A (t10), .B (n_47), .Y (n_51));
  OAI22XL g2151(.A0 (n_3), .A1 (n_35), .B0 (t15), .B1 (n_16), .Y
       (n_50));
  OAI211X1 g2152(.A0 (n_6), .A1 (n_10), .B0 (n_8), .C0 (n_37), .Y
       (n_49));
  NAND2XL g2153(.A (t20), .B (n_32), .Y (n_48));
  NAND2XL g2154(.A (n_38), .B (n_23), .Y (n_47));
  NOR2BX1 g2155(.AN (n_33), .B (n_12), .Y (n_46));
  INVX1 g2156(.A (n_44), .Y (n_45));
  NAND2XL g2157(.A (n_37), .B (n_23), .Y (n_44));
  OAI31X1 g2158(.A0 (n_24), .A1 (n_21), .A2 (n_25), .B0
       (next_state[2]), .Y (n_43));
  OAI21XL g2159(.A0 (n_3), .A1 (n_28), .B0 (t20), .Y (n_42));
  OAI21XL g2160(.A0 (t10), .A1 (n_16), .B0 (n_34), .Y (n_41));
  OAI211X1 g2161(.A0 (n_6), .A1 (n_19), .B0 (n_8), .C0 (n_26), .Y
       (n_40));
  OAI31X1 g2162(.A0 (n_5), .A1 (n_12), .A2 (n_22), .B0 (n_2), .Y
       (n_39));
  AND2X1 g2163(.A (n_27), .B (n_7), .Y (n_38));
  INVX1 g2164(.A (n_36), .Y (n_37));
  NAND2XL g2165(.A (t25), .B (n_26), .Y (n_36));
  NOR2XL g2166(.A (n_4), .B (n_28), .Y (n_35));
  NOR2XL g2167(.A (t30), .B (n_25), .Y (n_34));
  OAI21XL g2168(.A0 (t25), .A1 (n_21), .B0 (n_4), .Y (n_33));
  OAI21XL g2169(.A0 (t25), .A1 (n_20), .B0 (t15), .Y (n_32));
  NAND3BXL g2170(.AN (n_24), .B (n_9), .C (n_17), .Y (n_31));
  AOI22XL g2171(.A0 (state[2]), .A1 (n_19), .B0 (t30), .B1 (n_15), .Y
       (n_30));
  OAI221X1 g2172(.A0 (state[2]), .A1 (n_18), .B0 (t10), .B1 (n_13), .C0
       (n_0), .Y (n_29));
  NOR2XL g2173(.A (t30), .B (n_20), .Y (n_28));
  NOR2XL g2174(.A (t15), .B (n_24), .Y (n_27));
  AND3XL g2175(.A (t20), .B (t15), .C (n_9), .Y (n_26));
  OAI21XL g2177(.A0 (t10), .A1 (n_3), .B0 (n_23), .Y (n_25));
  DFFQXL \state_reg[0] (.CK (clk), .D (n_2), .Q (state[0]));
  DFFQXL \state_reg[1] (.CK (clk), .D (n_14), .Q (state[1]));
  DFFQXL \state_reg[2] (.CK (clk), .D (n_11), .Q (state[2]));
  NAND2XL g2181(.A (n_8), .B (n_16), .Y (n_24));
  INVX1 g2182(.A (n_23), .Y (n_22));
  NAND2XL g2183(.A (state[1]), .B (n_13), .Y (n_23));
  NOR2XL g2184(.A (n_3), .B (n_17), .Y (n_21));
  NAND2XL g2185(.A (state[2]), .B (n_10), .Y (n_20));
  NAND2XL g2186(.A (n_0), .B (n_18), .Y (n_19));
  NAND2BXL g2188(.AN (state[0]), .B (state[1]), .Y (n_18));
  NAND2XL g2190(.A (state[1]), .B (state[0]), .Y (n_17));
  NOR2XL g2191(.A (t25), .B (t20), .Y (n_16));
  NAND2XL g2192(.A (state[1]), .B (state[2]), .Y (n_15));
  AND2X1 g2193(.A (n_7), .B (next_state[1]), .Y (n_14));
  AND2X1 g2194(.A (state[2]), .B (state[0]), .Y (n_13));
  NOR2XL g2195(.A (t25), .B (n_8), .Y (n_12));
  AND2X1 g2197(.A (n_7), .B (next_state[2]), .Y (n_11));
  NOR2XL g2198(.A (state[0]), .B (state[1]), .Y (n_10));
  NOR2XL g2199(.A (reset), .B (n_5), .Y (n_9));
  INVX1 g2200(.A (t30), .Y (n_8));
  INVX1 g2201(.A (reset), .Y (n_7));
  INVX1 g2202(.A (state[2]), .Y (n_6));
  INVX1 g2203(.A (t10), .Y (n_5));
  INVX1 g2205(.A (t20), .Y (n_4));
  INVX1 g2206(.A (t15), .Y (n_3));
  AND2X1 g2207(.A (n_7), .B (next_state[0]), .Y (n_2));
  NAND4BX1 g2(.AN (n_25), .B (n_7), .C (n_46), .D (n_42), .Y (n_1));
  NAND2BX1 g2208(.AN (state[1]), .B (state[0]), .Y (n_0));
endmodule

